CREATE TABLE CUSTOMER (ID INTEGER not null primary key, FNAME VARCHAR(50) not null, LNAME VARCHAR(50) not null, AGE INTEGER not null)
CREATE TABLE ID_GEN (ID INTEGER not null primary key, VAL INTEGER)
